- examples/basic/main.tf
The example references the controlplane configuration for both the control plane and the worker nodes. This fixes that wrong reference.
> Fix wrong resource reference

- talos/util.go
In between Talos SDK updates the error message returned by the Talos SDK when using insecure client with a machine that already has a valid machineconfig has changed, updating the check to compare the old and new message.
Fixes: #28 
Signed-off-by: Noel Georgi <git@frezbo.dev>
> fix: handling talos secure client

- docs/resources/machine_configuration_controlplane.md
- docs/resources/machine_configuration_worker.md
- talos/resource_talos_machine_configuration_controlplane.go
- talos/resource_talos_machine_configuration_worker.go
The meaning of `talos_version`  in the `machine_configuration` resources might be confusing currently. This PR tries to clarify.
See #31
> docs: clarify meaning of `talos_version` in `machine_configuration` 

- talos/resource_talos_client_configuration.go
This PR fixes a bug where terraform was unable to apply when the number of control plane nodes was scaled from, for example, 1 to 3. This ensures that the talosconfig resource gets recreated any time the IPs in the list of endpoints or nodes is changed and that gets bubbled out to all of the other dependent objects. Seems to work well, tested with DO example.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> fix: force new talosconfig if endpoints or nodes change

- .github/workflows/acceptance-tests.yaml
- .github/workflows/pull-request.yaml
- hack/release.toml
Run acceptance tests only on provider file changes. Only run the basic checks on PR's.
> chore: ci cleanup

- docs/data-sources/cluster_kubeconfig.md
- docs/data-sources/machine_configuration.md
- docs/index.md
- docs/resources/machine_bootstrap.md
- docs/resources/machine_configuration_apply.md
- examples/data-sources/talos_cluster_kubeconfig/data-source.tf
- examples/data-sources/talos_machine_configuration/data-source.tf
- examples/resources/talos_machine_bootstrap/resource.tf
- examples/resources/talos_machine_configuration_apply/resource.tf
- templates/index.md.tmpl
When experimenting with the provider, it failed on the examples given in the documentation because it was using `type` instead of `machine_type`
> docs: replace `type` with `machine_type`

- docs/index.md
- templates/index.md.tmpl
This PR updates the link in our terraform provider docs to point to the contrib repo's terraform/ directory instead of calling out each environment one by one.
> docs: update link to contrib repo

- internal/talos/talos_cluster_kubeconfig_data_source.go
- internal/talos/talos_machine_bootstrap_resource.go
- internal/talos/talos_machine_configuration_apply_resource.go
- internal/talos/talos_machine_disks_data_source.go
- internal/talos/util.go
Fix node and endpoint being swapped for `kubeconfig` and `disks` data sources.
Fixes: #98
Signed-off-by: Noel Georgi <git@frezbo.dev>
(cherry picked from commit 5ac7183f33a425e17821f1a294a3133daa09e7fa)
> fix: node/endpoint were swapped for some resources.

- docs/data-sources/cluster_kubeconfig.md
- docs/data-sources/machine_disks.md
- docs/index.md
- docs/resources/machine_bootstrap.md
- docs/resources/machine_configuration_apply.md
- examples/data-sources/talos_machine_disks/data-source.tf
- examples/resources/talos_machine_bootstrap/resource.tf
- examples/resources/talos_machine_configuration_apply/resource.tf
- internal/talos/talos_cluster_kubeconfig_data_source.go
- internal/talos/talos_machine_disks_data_source.go
- templates/index.md.tmpl
This PR fixes a few random typos I found while perusing the documentation. `docs/resources/machine_bootstrap.md` and `docs/resources/machine_configuration_apply.md` both had an incorrect parameter shown in `talos_client_configuration` and should be `nodes` rather than `node` as shown here `internal/talos/talos_client_configuration_data_source.go#L25`
> docs: correct talos_client_configuration nodes parameter in examples

- .github/workflows/acceptance-tests.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/release.yml
- .vscode/launch.json
- Makefile
- README.md
- internal/talos/talos_machine_configuration_data_source.go
- internal/talos/talos_machine_configuration_data_source_test.go
- main.go
This fixes the talos_version parsing.
For some odd reason, while trying to use a terraform variable (please see the last commit at the branch at https://github.com/rgl/terraform-libvirt-talos/tree/wip-tfvars). this provider started to crash. This PR fixed that crash by now returning an "internal error" kind of message. But that still does not make my branch work!
Even thou this PR seems to be needed, I'm still stuck, I can now see this internal error, but I have no idea what I'm doing to trigger this in terraform.
PS: Oh, commenting the `kubernetes_version` property prevents the original crash from happening:
```yml
data "talos_machine_configuration" "controller" {
cluster_name       = var.cluster_name
cluster_endpoint   = local.cluster_endpoint
machine_secrets    = …
```
> fix talos_version nil parsing

- docs/data-sources/machine_configuration.md
- hack/release.toml
- pkg/talos/talos_machine_configuration_data_source.go
- pkg/talos/talos_machine_configuration_data_source_test.go
Generating talos machine configs with docs and examples enabled makes them too large. Fixes #181
> Default talos_machine_configuration docs and examples to false

- pkg/talos/talos_client_configuration_data_source.go
- pkg/talos/talos_cluster_health_data_source.go
- pkg/talos/talos_cluster_kubeconfig_data_source.go
- pkg/talos/talos_cluster_kubeconfig_resource.go
- pkg/talos/talos_machine_bootstrap_resource.go
- pkg/talos/talos_machine_configuration_apply_resource.go
- pkg/talos/talos_machine_configuration_data_source.go
- pkg/talos/talos_machine_disks_data_source.go
- pkg/talos/talos_machine_secrets_resource.go
Fix resourceplanmodifiers for `talos_cluster_kubeconfig_resource`. Also use pointer to set state everywhere, otherwise the provider shows some weird inconsistencies.
Part of: #203
> fix: resourceplanmodifiers for kubeconfig resource

- docs/resources/cluster_kubeconfig.md
- pkg/talos/talos_cluster_kubeconfig_data_source.go
- pkg/talos/talos_cluster_kubeconfig_resource.go
Support configurable cert refresh time for `talos_cluster_kubeconfig`.
Fixes: #203
> feat: configurable cert refresh time for kubeconfig

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.1 release.
> release(v0.6.1): prepare release

- pkg/talos/talos_machine_configuration_data_source.go
- pkg/talos/talos_machine_configuration_data_source_test.go
We don't have correct way of knowing which talos version or the k8s version the cluster is currently running, so drop the check which was based on talos version contract which would prevent setting kubernetes version if the cluster was initially created with an old version contract.
Fixes: #228
> fix: drop talos<->k8s compatibility check

- CHANGELOG.md
- hack/release.toml
This is the official v0.8.0-alpha.0 release.
> release(v0.8.0-alpha.0): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.8.0 release.
> release(v0.8.0): prepare release

- docs/data-sources/image_factory_urls.md
- examples/data-sources/talos_image_factory_urls/data-source.tf
This stumped me for a while today, until I read the docs more closely. Turns out `installer_image` is not a valid attribute on `talos_image_factory_urls`.
> docs: fix reference to non-existing attribute in talos_image_factory_urls docs

- pkg/talos/talos_image_factory_urls_data_source.go
- pkg/talos/talos_image_factory_urls_data_source_test.go
This pull request fixes #247 
It parses the provided talos_version argument and checks that it can be converted to a Semantic Version, if it can it is converted into a string and prefixed with "v".
> feat: sanitize the version arg in the urls data source

- CHANGELOG.md
- hack/release.toml
This is the official v0.9.0-alpha.0 release.
> release(v0.9.0-alpha.0): prepare release
