CHANGELOG.md, Makefile, hack/release.toml
This is the official v0.1.0-alpha.5 release.
Signed-off-by: Noel Georgi <git@frezbo.dev>
=> release(v0.1.0-alpha.5): prepare release

.gitignore, CHANGELOG.md, hack/release.toml
This is the official v0.1.0-alpha.6 release.
Signed-off-by: Noel Georgi <git@frezbo.dev>
=> release(v0.1.0-alpha.6): prepare release

CHANGELOG.md
This is the official v0.1.2 release.
=> release(v0.1.2): prepare release

CHANGELOG.md
This is the official v0.2.0-alpha.0 release.
=> release(v0.2.0-alpha.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.2.0-alpha.1 release.
=> release(v0.2.0-alpha.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.2.0-beta.0 release.
=> release(v0.2.0-beta.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official 0.2.1 release.
=> release(0.2.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official 0.3.0-beta.0 release.
=> release(0.3.0-beta.0): prepare release

internal/talos/util.go
Don't depend on error message strings to identify if we need to create a secure client.
=> fix: creation of talos client

CHANGELOG.md, hack/release.toml
This is the official 0.3.1 release.
=> release(0.3.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official 0.3.2 release.
=> release(0.3.2): prepare release

.conform.yaml
=> chore: add conform

CHANGELOG.md, hack/release.toml
This is the official v0.4.0-alpha.0 release.
=> release(v0.4.0-alpha.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.3.3 release.
=> release(v0.3.3): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.3.4 release.
=> release(v0.3.4): prepare release

.github/workflows/slack-notify.yaml
Add the missing slack workflow.
=> chore: add the missing slack workflow

CHANGELOG.md, hack/release.toml
This is the official v0.5.0 release.
=> release(v0.5.0): prepare release

docs/data-sources/cluster_health.md, pkg/talos/talos_cluster_health_data_source.go
Update description of `talos_cluster_health` data source.
Fixes: #129
=> docs: update description of `talos_cluster_health`

CHANGELOG.md, go.mod, hack/release.toml
This is the official v0.6.0-alpha.0 release.
=> release(v0.6.0-alpha.0): prepare release

CHANGELOG.md, hack/release.sh
This is the official v0.6.0-alpha.2 release.
=> release(v0.6.0-alpha.2): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.7.0-alpha.0 release.
=> release(v0.7.0-alpha.0): prepare release

CHANGELOG.md
This is the official v0.7.0 release.
=> release(v0.7.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.7.1 release.
=> release(v0.7.1): prepare release

.conform.yaml, pkg/talos/talos_image_factory_urls_data_source.go, pkg/talos/talos_image_factory_urls_data_source_test.go, pkg/talos/talos_image_factory_versions_data_source_test.go
See:
* https://github.com/siderolabs/terraform-provider-talos/pull/256
* https://github.com/siderolabs/terraform-provider-talos/pull/253
=> chore: backports for v0.8.1

CHANGELOG.md, hack/release.toml
This is the official v0.8.1 release.
=> release(v0.8.1): prepare release

go.mod, pkg/talos/talos_machine_disks_data_source.go
Simplify disk selector code, this also drops direct dependency on COSI.
=> chore: simplify disk selector code
